/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Foo {
  col_int: number;
  col_int_null: number | null;
  col_real: number;
  col_real_null: number | null;
  col_text: string;
  col_text_null: string | null;
  col_timestamp: number;
  col_timestamp_null: number | null;
}

export interface DB {
  foo: Foo;
}
